# version: 2.1

# orbs:
#   win: circleci/windows@2.2.0

# jobs:
#   build:
#     executor:
#       name: win/default
#     steps:
#       # default shell is Powershell
#       - run:
#          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
#          shell: powershell.exe
#       - run:
#          command: echo hello && echo world
#          shell: bash.exe
#       - run:
#          command: echo hello & echo world
#          shell: cmd.exe
#       - checkout
#       - run: dotnet tool install --global PowerShell
#       - run: pwsh ./<a-script>.ps1

version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool install --global PowerShell --version 6.2.2
      - run: pwsh ./a-script.ps1